version: '3.9'

services:
  db:
    image: postgres
    container_name: db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_USER=postgres
      - POSTGRES_DB=warehouse
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: warehouse
    depends_on:
      - db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/warehouse
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=mysecretpassword
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"